### ISSUE TITLE
Getting nullpointer exception : LensEngine LensAnalyzerRunable on using it second time

### ISSUE THREAD

**Issue by rohitgarg29** [HMS-Core/hms-ml-demo#52]
Hi,

I am using this example to scan the ID card, it is working fine but when i am trying to scan it 2nd time, it is giving me null pointer exception. 

Exception thrown from receiver.
    java.lang.NullPointerException: *t*e*p* *o*i*v*k* *i*t*a* *e*h*d*'*o*d*c*m*h*a*e*.*m*.*l*d*.*o*m*n*M*A*a*y*e*.*b*a*n*i*t*r*(*o*.*u*w*i*h*s*m*s*k*c*m*o*.*L*r*m*)* *n*a*n*l* *b*e*t*r*f*r*n*e
        at com.huawei.hms.mlsdk.common.LensEngine$LensAnalyzerRunable.run(LensEngine.java:734)
        at java.lang.Thread.run(Thread.java:929)

plus any reason for getting below logs

forbiddenHiLog.getVenderCountry=meafnaf
forbiddenHiLog openHa = true

Thanks in advance for your help.

**Comment by Mike-mei** [comment]
@rohitgarg29 
Please firstly check which integration way you are using
1. Full SDK integration: only one dependency needs to be added, and upgrade ml-computer-card-icr-cn to the latest 2.0.3.300 version，
2. Basic SDK integration: only one dependency needs to be added, adn upgrade ml-computer-card-icr-cn-plugin to the latest 2.0.3.300 version
