### ISSUE TITLE
ML Body 闪退

### ISSUE THREAD

**Issue by 15665822135** [HMS-Core/hms-ml-demo#82]
2021-11-24 17:38:28.624 11628-11628/com.mlkit.sample.body E/libc: Access denied finding property "ro.vendor.scroll.preobtain.enable"
2021-11-24 17:38:28.653 11628-11738/com.mlkit.sample.body E/linker: library "" ("/apex/com.android.vndk.v30/lib64") needed or dlopened by "/apex/com.android.vndk.v30/lib64/libRS_internal.so" is not accessible for the namespace: [name="rs", ld_library_paths="", default_library_paths="/apex/com.android.vndk.v30/lib64:/vendor/lib64", permitted_paths="/odm/lib64:/vendor/lib64:/system/vendor/lib64:/data"]
2021-11-24 17:38:29.709 11628-11628/com.mlkit.sample.body E/HaLogProvider: forbiddenHiLog.getVenderCountry=UNKNOWN
2021-11-24 17:38:29.709 11628-11628/com.mlkit.sample.body E/HaLogProvider: forbiddenHiLog openHa = false
2021-11-24 17:38:29.723 11628-11785/com.mlkit.sample.body E/CountryCodeBean: getVendorCountry=UNKNOWN
2021-11-24 17:38:29.723 11628-11785/com.mlkit.sample.body E/CountryCodeBean: getSimCountryCode by not enableNetwork, countryCode=cn
2021-11-24 17:38:29.747 11628-11785/com.mlkit.sample.body E/HaLogProvider: forbiddenHiLog.getVenderCountry=UNKNOWN
2021-11-24 17:38:29.747 11628-11785/com.mlkit.sample.body E/HaLogProvider: forbiddenHiLog openHa = false
2021-11-24 17:38:29.752 11628-11783/com.mlkit.sample.body E/HIAI_DDK_MSG: IsLegacyRomItf: Current rom verison not support NPU.
2021-11-24 17:38:29.752 11628-11783/com.mlkit.sample.body E/HIAI_DDK_MSG: IsLegacyRomItf: Current rom verison not support NPU.
2021-11-24 17:38:29.790 11628-11785/com.mlkit.sample.body E/HaLogProvider: forbiddenHiLog.getVenderCountry=UNKNOWN
2021-11-24 17:38:29.790 11628-11785/com.mlkit.sample.body E/HaLogProvider: forbiddenHiLog openHa = false

手机型号：
vivo iqoo pro 5g（V1916A）
android 11
OriginOS1.0

**Comment by 15665822135** [comment]
打开不是闪退就是ANR

**Comment by 15665822135** [comment]
2021-11-24 17:49:19.027 18264-18264/com.mlkit.sample.body E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mlkit.sample.body, PID: 18264
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at com.huawei.mlkit.sample.camera.LensEngine$FrameTransactingRunnable.release(LensEngine.java:254)
        at com.huawei.mlkit.sample.camera.LensEngine.release(LensEngine.java:76)
        at com.huawei.mlkit.sample.activity.face.FaceDetectionActivity.releaseLensEngine(FaceDetectionActivity.java:211)
        at com.huawei.mlkit.sample.activity.face.FaceDetectionActivity.onBackPressed(FaceDetectionActivity.java:206)
        at android.app.Activity.onKeyUp(Activity.java:3883)
        at android.view.KeyEvent.dispatch(KeyEvent.java:3012)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4189)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:115)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:133)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:447)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6442)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6273)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5738)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5805)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5928)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5774)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5985)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5742)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5805)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5774)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5742)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5805)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5961)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6126)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3397)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2939)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2930)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3374)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:339)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:8209)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by 15665822135** [comment]
每次关闭模块界面（例如：人脸检测、人体骨骼、手势识别等模块）必定闪退

**Comment by Mike-mei** [comment]
为了方便我们快速进行问题定位，请提供一份日志，以及使用的SDK版本

**Comment by 15665822135** [comment]
我就是克隆的当前工程运行，崩溃日志咱们工程存放到哪里了？

> 

我就是克隆的当前工程运行，崩溃日志咱们工程存放到哪里了？

**Comment by 15665822135** [comment]
> 为了方便我们快速进行问题定位，请提供一份日志，以及使用的SDK版本

我就是克隆的当前工程运行，崩溃日志咱们工程存放到哪里了？

**Comment by 15665822135** [comment]
运行的这个model
 modulebody
    |-- com.mlkit.sample
        |-- Activity
            |-- FaceDetectionActivity //人脸检测
            |-- Live3DFaceAnalyseActivity //3D人脸检测
            |-- FaceVerificationActivity // 人脸比对
            |-- HumanSkeletonActivity //人体骨骼
            |-- TemplateActivity //骨骼模板选择类
            |-- HumanLivenessDetectionActivity // 活体检测
            |-- HandKeypointActivity // 手部关键点
            |-- HandKeypointImageActivity // 手部关键点静态检测
            |-- GestureActivity // 手势识别
            |-- GestureImageActivity // 手势识别静态检测
            |-- BaseActivity  // Activity基类
            |-- StartActivity  // 服务入口
            |-- SettingActivity  // modulebody基本信息

**Comment by 15665822135** [comment]
运行的MLKit-Sample 工程的这个model
modulebody
|-- com.mlkit.sample
|-- Activity
|-- FaceDetectionActivity //人脸检测
|-- Live3DFaceAnalyseActivity //3D人脸检测
|-- FaceVerificationActivity // 人脸比对
|-- HumanSkeletonActivity //人体骨骼
|-- TemplateActivity //骨骼模板选择类
|-- HumanLivenessDetectionActivity // 活体检测
|-- HandKeypointActivity // 手部关键点
|-- HandKeypointImageActivity // 手部关键点静态检测
|-- GestureActivity // 手势识别
|-- GestureImageActivity // 手势识别静态检测
|-- BaseActivity // Activity基类
|-- StartActivity // 服务入口
|-- SettingActivity // modulebody基本信息

**Comment by Mike-mei** [comment]
基于能力的代码是没有问题的，麻烦您先参考基本能力示例代码：https://developer.huawei.com/consumer/cn/doc/development/hiai-Examples/sample-code-0000001050265470
